apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/kubernetes-sigs/gateway-api//config/crd?ref=v1.0.0
  - github.com/pl4nty/cloudflare-kubernetes-gateway//config/crd?ref=v0.8.1

# Add this annotation to your CRD files
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Install before everything else
